#!/bin/bash

set -e

# Program to install docker and docker compose

DOCKER_URL="https://download.docker.com/linux/centos/docker-ce.repo"
COMPOSE_URL="https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)"

# Install Docker

sudo yum install -y yum-utils device-mapper-persistent-data lvm2 \
&& sudo yum-config-manager --add-repo $DOCKER_URL \
&& sudo yum install docker-ce \
&& sudo systemctl start docker.service \

# Install Docker Compose

sudo curl -L "$COMPOSE_URL" -o /usr/local/bin/docker-compose \
&& sudo chmod +x /usr/local/bin/docker-compose \
&& docker-compose --version \

# Apache with port 8080

cd \
&& mkdir ./dc_apache \
&& mkdir ./dc_apache/html_files \
&& cd ./dc_apache/html_files \
&& cat > apache.html <<- _EOF_
<HTML>
<HEAD>
<TITLE>Apache 8080</TITLE>
</HEAD>
<BODY>
Hi Apache.
</BODY>
</HTML>
_EOF_

chmod +x apache.html \
&& cd .. \
&& cat > Dockerfile <<- _EOF_
        FROM httpd:2.4
        WORKDIR /var/www/html
        COPY ./html_files/ /var/www/html
_EOF_

chmod +x Dockerfile \
&& docker build -t my-apache2 . \
&& docker run -dit --name my-running-app -p 8080:80 my-apache2 \
&& echo "Visit http://localhost:8080/ and check if it works properly." \
&& read -e -p "Press Enter to continue > " \

# Visit http://localhost:8080/public-html and you will see it works!

# Nginx with port 80

cd \
&& mkdir ./dc_nginx \
&& mkdir ./dc_nginx/html_files \
&& cd ./dc_nginx/html_files \
&& cat > nginx.html <<- _EOF_
<HTML>
<HEAD>
<TITLE>Nginx 80</TITLE>
</HEAD>
<BODY>
Hi Nginx.
</BODY>
</HTML>
_EOF_

chmod +x nginx.html \
&& cd .. \
&& cat > Dockerfile <<- _EOF_
        FROM nginx
        WORKDIR /usr/share/nginx/html
        COPY ./html_files/ /usr/share/nginx/html
_EOF_

chmod +x Dockerfile \
&& docker build -t some-content-nginx . \
&& docker run --name some-nginx -d -p 80:80 some-content-nginx \
&& echo "Visit http://localhost:80 and check if it works properly." \
&& read -e -p "Press Enter to continue > " \

# Visit http://localhost/static-html-directory and you will see it works!

# MariaDB with port 3306

cd \
&& mkdir ./dc_mariadb \
&& docker run --name mysql_test -p 3306:3306 -e MYSQL_ROOT_PASSWORD=test -d mariadb/server:10.3 \
&& echo "Access this MySQL container with the following details and check how it works: name = mysql_test / password = test / hostname = localhost / port = 3306" \
&& read -e -p "Press Enter to end the work of the script > " \
